# Generated by Django 4.2.8 on 2024-06-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyHoursPerWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='have_a_laptop',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=500, verbose_name='Have a laptop?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AboutCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=500, null=True)),
                ('employment_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=500)),
                ('have_a_laptop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=500, verbose_name='Have a laptop?')),
                ('annual_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.annualincome')),
                ('computer_skill_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.computerskilllevel')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.educationlevel')),
                ('study_hours_per_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.studyhoursperweek')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='annual_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.annualincome'),
        ),
        migrations.AddField(
            model_name='profile',
            name='computer_skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.computerskilllevel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.educationlevel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_hours_per_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.studyhoursperweek'),
        ),
    ]
