# Generated by Django 4.2.8 on 2024-06-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_citizenshipstatus_ethnicity_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualincome',
            name='income',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
