# Generated by Django 4.2.8 on 2024-06-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_degreefocus_yearsofexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearsofexperience',
            name='year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
