# Generated by Django 4.2.8 on 2024-06-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_yearsofexperience_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcandidate',
            name='degree_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.degreefocus'),
        ),
        migrations.AddField(
            model_name='aboutcandidate',
            name='years_of_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.yearsofexperience'),
        ),
    ]
