# Generated by Django 4.2.8 on 2024-06-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_profile_degree_focus_profile_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerprogramselection',
            name='program',
        ),
        migrations.RemoveField(
            model_name='registerprogramselection',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='registerprogramselection',
            name='start_date',
        ),
    ]
