# Generated by Django 4.2.8 on 2024-07-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_paymentplan_profile_payment_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_schedule', to='dashboard.paymentplan')),
            ],
        ),
    ]
