# Generated by Django 4.2.8 on 2024-07-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_paymentplanwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='duration_in_days',
            field=models.IntegerField(blank=True, help_text='Enter the payment duration', null=True),
        ),
    ]
