# Generated by Django 4.2.8 on 2024-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_paymentplan_duration_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the percentage of the payment to make', max_digits=4, null=True),
        ),
    ]
