# Generated by Django 4.2.8 on 2024-07-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_paymentplan_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the percentage of the payment to make', max_digits=5, null=True),
        ),
    ]
