# Generated by Django 4.2.8 on 2024-07-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_paymentplanwidget_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_plan_selection_completed',
            field=models.BooleanField(default=False),
        ),
    ]
