# Generated by Django 4.2.8 on 2024-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_profile_payment_plan_selection_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
