# Generated by Django 4.2.8 on 2024-06-18 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_category', to='courses.programcategory'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='delivery_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_mode', to='courses.deliverymode'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_program_type', to='courses.programtype'),
        ),
    ]
