# Generated by Django 4.2.8 on 2024-06-25 16:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_delivery_mode_remove_course_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hero_carousel_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Please make this very short', null=True),
        ),
    ]
