# Generated by Django 5.0.6 on 2024-05-30 23:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_curriculum_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='course_tip_1',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='course_tip_2',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
