# Generated by Django 4.2.8 on 2024-07-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_profile_payment_courseschedule_and_more'),
        ('courses', '0007_course_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
    ]
