# Generated by Django 5.0.6 on 2024-05-31 02:19

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_body_locationschedule_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationschedule',
            name='location',
            field=wagtail.fields.StreamField([('intro', wagtail.blocks.RichTextBlock(required=False)), ('location_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('map_url', wagtail.blocks.URLBlock(required=False)), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True),
        ),
    ]
