# Generated by Django 4.2.8 on 2024-06-07 08:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProgram',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading_title', models.CharField(blank=True, max_length=500, null=True)),
                ('banner', cloudinary.models.CloudinaryField(blank=True, help_text='upload image banner to display.', max_length=255, null=True)),
                ('intro', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MeetLeadership',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading_title', models.CharField(blank=True, max_length=500, null=True)),
                ('banner', cloudinary.models.CloudinaryField(blank=True, help_text='upload image banner to display.', max_length=255, null=True)),
                ('contents', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
