# Generated by Django 4.2.8 on 2024-06-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_getinfoformpage_getinfoformsettings_formfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfoformsettings',
            old_name='request_form_page',
            new_name='get_info_form_page',
        ),
    ]
