# Generated by Django 4.2.8 on 2024-06-08 14:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerServices',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading_title', models.CharField(blank=True, max_length=500, null=True)),
                ('banner', cloudinary.models.CloudinaryField(blank=True, help_text='upload image banner to display.', max_length=255, null=True)),
                ('introduction', wagtail.fields.StreamField([('intro_text', wagtail.blocks.RichTextBlock(required=False)), ('column1', wagtail.blocks.RichTextBlock(required=False)), ('column2', wagtail.blocks.RichTextBlock(required=False)), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True)),
                ('career_building', wagtail.fields.StreamField([('intro_text', wagtail.blocks.RichTextBlock(required=False)), ('path1', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])), ('path2', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])), ('path3', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True)),
                ('ad', wagtail.fields.RichTextField(blank=True, null=True)),
                ('career_services_glance', wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(required=False)), ('intro', wagtail.blocks.RichTextBlock(required=False)), ('column1', wagtail.blocks.RichTextBlock(required=False)), ('column2', wagtail.blocks.RichTextBlock(required=False)), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True)),
                ('dedicated_support', wagtail.fields.StreamField([('introduction', wagtail.blocks.RichTextBlock(required=False)), ('support1', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False))])), ('support2', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False))])), ('support3', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False))])), ('support4', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False))])), ('support5', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False))])), ('support6', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False))])), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True)),
                ('employment_readiness', wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(required=False)), ('intro', wagtail.blocks.RichTextBlock(required=False)), ('column1', wagtail.blocks.RichTextBlock(required=False)), ('column2', wagtail.blocks.RichTextBlock(required=False)), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True)),
                ('future_support', wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True)),
                ('faq', wagtail.fields.StreamField([('faq1', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=False)), ('answer', wagtail.blocks.RichTextBlock(required=False))])), ('faq2', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=False)), ('answer', wagtail.blocks.RichTextBlock(required=False))])), ('faq3', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=False)), ('answer', wagtail.blocks.RichTextBlock(required=False))])), ('faq4', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=False)), ('answer', wagtail.blocks.RichTextBlock(required=False))])), ('faq5', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=False)), ('answer', wagtail.blocks.RichTextBlock(required=False))])), ('faq6', wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock(required=False)), ('answer', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='studentsupport',
            name='introduction',
        ),
        migrations.AddField(
            model_name='studentsupport',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
