# Generated by Django 4.2.8 on 2024-06-08 15:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_careerservices_remove_studentsupport_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerservices',
            name='career_building',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(required=False)), ('intro_text', wagtail.blocks.RichTextBlock(required=False)), ('path1', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])), ('path2', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])), ('path3', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerservices',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsupport',
            name='intro',
            field=wagtail.fields.StreamField([('intro_text', wagtail.blocks.RichTextBlock(required=False)), ('column1', wagtail.blocks.RichTextBlock(required=False)), ('column2', wagtail.blocks.RichTextBlock(required=False)), ('more_text', wagtail.blocks.RichTextBlock(required=False))], blank=True, null=True),
        ),
    ]
